// <auto-generated />
namespace BrouwerijWittig.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddChangeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChangeId));
        
        string IMigrationMetadata.Id
        {
            get { return "202603081751461_AddChangeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
